name: Coverage Report

on:
  #events
  push:
    branches: [ "main", "Develop" ]
  pull_request:
    branches: [ "main", "Develop" ]

jobs:
  # only one job per workflow here it is build
  coverage:
    # runs on ubuntu virtual machine
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up python 3.12
        uses: actions/setup-python@v3
        with:
          # python version is 3.12
          python-version: 3.12

      - name: Install dependencies
        # commands; pipe symbol is used to put multiple lines of commands
        run: |
          cd Source
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Coverage report
        # coverage measurement of tests
        run: |
          cd Source
          coverage run manage.py test
          coverage report
